# Schwab API Library Configuration
schwab:
  api:
    urls:
      auth: "https://api.schwabapi.com/v1/oauth/authorize"
      token: "https://api.schwabapi.com/v1/oauth/token"
      traderBase: "https://api.schwabapi.com/trader/v1"
      marketData: "https://api.schwabapi.com/marketdata/v1"
    
    defaults:
      redirectUri: "https://127.0.0.1"
      httpTimeoutMs: 3000

# Logging for the API library
logging:
  level:
    com.higgstx.schwabapi: INFO
    okhttp3: WARN